name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Log in to Docker Hub
        shell: powershell
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $env:DOCKER_PASSWORD | docker login --username $env:DOCKER_USERNAME --password-stdin

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull cpajitha/fastapi_app:latest
          docker tag cpajitha/fastapi_app:latest fastapi_app:latest

      - name: Deploy to Server
        run: |
          docker stop fastapi_container || true
          docker rm fastapi_container || true
          docker run -d --name fastapi_container -p 8000:8000 fastapi_app:latest
          echo "✅ Deployment successful!"
