name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cpajitha/fastapi_app:latest .

      - name: Log in to Docker Hub
        shell: powershell
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $env:DOCKER_PASSWORD | docker login --username $env:DOCKER_USERNAME --password-stdin

      - name: Push Docker image
        run: docker push cpajitha/fastapi_app:latest

      - name: Deploy to Server
        run: |
          echo "Deploying application..."
          # Add your actual deployment commands here
